# Generated by Django 3.2 on 2025-11-04 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_invitation_organizationmember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('member', 'Member')], default='member', max_length=20),
        ),
    ]
